name: Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest

    container:
      image: tobix/pywine:3.13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Wine prefix
        run: |
          . /opt/mkuserwineprefix

      - name: Show all Python installations inside Wine
        run: |
          echo "Searching for python installations..."
          find /opt/wineprefix -iname "python.exe" -print

      - name: Define PYWINE variable
        run: |
          echo 'PYWINE=wine /opt/wineprefix/drive_c/Python/python.exe' >> $GITHUB_ENV

      - name: Install Python requirements via Wine
        run: |
          $PYWINE -m pip install -r requirements.txt --no-warn-script-location

      - name: Build executable (PyInstaller via Wine)
        run: |
          $PYWINE -m PyInstaller --clean --noconsole FarbenWolf.spec
          mkdir -p release
          zip -r release/FarbenWolf.zip dist/

      - name: Upload artifact (only on main branch)
        #if: |
        #  startsWith(github.ref, 'refs/heads/main') ||
        #  startsWith(github.ref, 'refs/pull/')
        uses: actions/upload-artifact@v4
        with:
          name: farbenwolf-build
          path: release/FarbenWolf.zip


  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: farbenwolf-build
          path: release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: release/FarbenWolf.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}