name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Build executable (PyInstaller)
        run: |
          pyinstaller --clean FarbenWolf.spec
          if (!(Test-Path release)) { New-Item -ItemType Directory -Path release }
          Compress-Archive -Path dist\* -DestinationPath release\FarbenWolf.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: farbenwolf-build
          path: release\FarbenWolf.zip


  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-chglog
        run: |
          curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v0.15.4/git-chglog_0.15.4_linux_amd64.tar.gz \
            -o git-chglog.tar.gz
          tar -xzf git-chglog.tar.gz
          chmod +x git-chglog
          sudo mv git-chglog /usr/local/bin/git-chglog

      - name: Generate CHANGELOG
        run: |
          git-chglog ${{ github.ref_name }} > CHANGELOG_NEW.md
          tail -n +2 CHANGELOG.md > CHANGELOG_OLD.md
          {
            echo "# CHANGELOG"
            echo ""
            cat CHANGELOG_NEW.md
            echo ""
            cat CHANGELOG_OLD.md
          } > CHANGELOG.md

      - name: Upload CHANGELOG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md

      - name: Generate Release Note
        run: |
          git-chglog --template .chglog/RELEASE_NOTE.tpl.md ${{ github.ref_name }} > RELEASE_NOTE.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: release/FarbenWolf.zip
          body_path: RELEASE_NOTE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}